const MIN_RANDOM_NUMBER = 0;
const MAX_RANDOM_NUMBER = 9;
const MOVE_THRESHOLD = 4;
const MIN_CAR_NAME_LENGTH = 1;
const MAX_CAR_NAME_LENGTH = 5;
const MOVING_DISTANCE_SYMBOL = '-';

export {
  MIN_RANDOM_NUMBER,
  MAX_RANDOM_NUMBER,
  MOVE_THRESHOLD,
  MIN_CAR_NAME_LENGTH,
  MAX_CAR_NAME_LENGTH,
  MOVING_DISTANCE_SYMBOL,
}