const MIN_RANGE_NUMBER = 0;
const MAX_RANGE_NUMBER = 9;
const MIN_MOVE_NUMBER = 4;
const MAX_CARNAME_LENGTH = 5;

export {
  MIN_RANGE_NUMBER,
  MAX_RANGE_NUMBER,
  MIN_MOVE_NUMBER,
  MAX_CARNAME_LENGTH,
};
