export const GAME_RULL = Object.freeze({
  DIVISION: ',',
  PLAYER_MIN_NUMBER: 2,
  PLAYER_MAX_NUMBER: 10,
  CAR_NAME_MAX_LENGTH: 5,
  MOVE_MAX_COUNT: 10,
  MOVE_MIN_COUNT: 1,
  START_PICK_NUMBER: 0,
  END_PICK_NUMBER: 9,
  MOVE_CONDITION_COUNT: 4,
});

export const STEP_SYMBOL = '-';
