const GAME_OPTION = Object.freeze({
  MIN_CAR_NAME_LENGTH: 1,
  MAX_CAR_NAME_LENGTH: 5,
  FORWARD_CONDITION_FROM: 0,
  FORWARD_CONDITION_TO: 4,
  FORWARD_INDICATOR: '-',
  INPUT_SEPARATOR: ',',
});

export default GAME_OPTION;
