const MAX_CARLIST_LENGTH = 10;

const MIN_CARLIST_LENGTH = 2;

const MAX_CAR_NAME_LENGTH = 5;

const MIN_FOWARD_NUMBER = 4;

const MIN_RANDOM_NUMBER_RANGE = 0;

const MAX_RANDOM_NUMBER_RANGE = 9;

const NUMBERS = {
  MAX_CARLIST_LENGTH,
  MIN_CARLIST_LENGTH,
  MAX_CAR_NAME_LENGTH,
  MIN_FOWARD_NUMBER,
  MIN_RANDOM_NUMBER_RANGE,
  MAX_RANDOM_NUMBER_RANGE,
};

export default NUMBERS;
