const MAX_CAR_NAME_LENGTH = 5
const MIN_CAR_NAME_LENGTH = 1
const MIN_ATTEMPT_NUMBER = 0

const MIN_MOVE_NUMBER = 4

export {MAX_CAR_NAME_LENGTH, MIN_CAR_NAME_LENGTH, MIN_ATTEMPT_NUMBER, MIN_MOVE_NUMBER}