const CONSTANTS = {
  MIN_DISTANCE: 0,
  MAX_DISTANCE: 9,
  MIN_MOVE_VALUE: 4,
  MIN_NAME_LENGTH: 5,
};
const ERROR_MESSAGE = {
  ERROR_CAR_NAME_LENGTH_EXCEED: "[ERROR]이름의 길이가 5자를 초과합니다.",
  ERROR_INPUT_NOT_BETWEEN_MIN_MAX: `[ERROR]입력값이 ${CONSTANTS.MIN_DISTANCE}~${CONSTANTS.MAX_DISTANCE} 범위의 숫자가 아닙니다.`,
  ERROR_INPUT_NOT_A_NUMBER: "[ERROR]입력값이 숫자가 아닙니다",
};

export {CONSTANTS,ERROR_MESSAGE};