const MAX_LENGTH_FOR_CAR_NAME = 5;
const INITIAL_DISTANCE = 0;

const RANDOM_INTEGER_MIN = 0;
const RANDOM_INTEGER_MAX = 9;
const MIN_VALUE_FOR_MOVE = 4;
const MOVEMENT_UNIT = 1;

const CAR_NAME_INPUT_SEPARATOR = ',';
const WINNERS_OUTPUT_SEPARATOR = ', ';
const DISTANCE_UNIT = '-';

export {
  MAX_LENGTH_FOR_CAR_NAME,
  INITIAL_DISTANCE,
  CAR_NAME_INPUT_SEPARATOR,
  WINNERS_OUTPUT_SEPARATOR,
  DISTANCE_UNIT,
  RANDOM_INTEGER_MIN,
  RANDOM_INTEGER_MAX,
  MIN_VALUE_FOR_MOVE,
  MOVEMENT_UNIT,
};
